spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_hibernate
    username: postgres
    password: krya
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use "update" for development; be careful in production
    show-sql: true # Print SQL statements in the console for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


